server:
  port: 8080


  datasource:
    url: jdbc:postgresql://postgresqldb:5432/oauthdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: hrhk
    initialization-mode: always

  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true
    properties.hibernate:
      show_sql: true
      format_sql: true



logging.level:
  org.springframework: info
  org.hibernate.SQL: DEBUG